services:
  postgres:
    image: postgres:17-alpine
    shm_size: 1gb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: let-me-in
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "${DEGOV_DB_PORT:-7453}:5432"

  indexer:
    image: degov-indexer
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: docker/indexer.Dockerfile
    ports:
      - "${DEGOV_INDEXER_PORT:-4350}:4350"
    environment:
      DB_HOST: postgres
      DB_NAME: indexer
      DB_USER: postgres
      DB_PASS: let-me-in
      DB_PORT: 5432
      GQL_PORT: 4350
      DEGOV_SYNC_ENDPOINT: http://web:3000/api/degov/sync
      DEGOV_SYNC_AUTH_TOKEN: 69a61f05a147f65fe27a654cd5b98e07

  web:
    image: degov-web
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "0.0.0.0:${DEGOV_WEB_PORT:-3002}:3000"
    environment:
      JWT_SECRET_KEY: 575276a8eb83abc2
      DATABASE_URL: postgresql://postgres:let-me-in@postgres:5432/degov
      DEGOV_SYNC_AUTH_TOKEN: 69a61f05a147f65fe27a654cd5b98e07
