services:
  postgres:
    image: postgres:17-alpine
    shm_size: 1gb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: let-me-in
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - "${DEGOV_DB_PORT:-7453}:5432"
  indexer:
    image: degov-indexer
    depends_on:
      - postgres
    build:
      context: packages/indexer
      dockerfile: docker/Dockerfile
    ports:
      - "${DEGOV_INDEXER_PORT:-4350}:4350"
    environment:
      DB_HOST: postgres
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: let-me-in
      DB_PORT: 5432
      GQL_PORT: 4350
