/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TreasuryImport } from './routes/treasury'
import { Route as ProposalsImport } from './routes/proposals'
import { Route as MembersImport } from './routes/members'
import { Route as DelegateImport } from './routes/delegate'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TreasuryRoute = TreasuryImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRoute,
} as any)

const ProposalsRoute = ProposalsImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRoute,
} as any)

const MembersRoute = MembersImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRoute,
} as any)

const DelegateRoute = DelegateImport.update({
  id: '/delegate',
  path: '/delegate',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/delegate': {
      id: '/delegate'
      path: '/delegate'
      fullPath: '/delegate'
      preLoaderRoute: typeof DelegateImport
      parentRoute: typeof rootRoute
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersImport
      parentRoute: typeof rootRoute
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsImport
      parentRoute: typeof rootRoute
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delegate': typeof DelegateRoute
  '/members': typeof MembersRoute
  '/proposals': typeof ProposalsRoute
  '/treasury': typeof TreasuryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delegate': typeof DelegateRoute
  '/members': typeof MembersRoute
  '/proposals': typeof ProposalsRoute
  '/treasury': typeof TreasuryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/delegate': typeof DelegateRoute
  '/members': typeof MembersRoute
  '/proposals': typeof ProposalsRoute
  '/treasury': typeof TreasuryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/delegate' | '/members' | '/proposals' | '/treasury'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/delegate' | '/members' | '/proposals' | '/treasury'
  id: '__root__' | '/' | '/delegate' | '/members' | '/proposals' | '/treasury'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DelegateRoute: typeof DelegateRoute
  MembersRoute: typeof MembersRoute
  ProposalsRoute: typeof ProposalsRoute
  TreasuryRoute: typeof TreasuryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DelegateRoute: DelegateRoute,
  MembersRoute: MembersRoute,
  ProposalsRoute: ProposalsRoute,
  TreasuryRoute: TreasuryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/delegate",
        "/members",
        "/proposals",
        "/treasury"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/delegate": {
      "filePath": "delegate.tsx"
    },
    "/members": {
      "filePath": "members.tsx"
    },
    "/proposals": {
      "filePath": "proposals.tsx"
    },
    "/treasury": {
      "filePath": "treasury.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
