/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TreasuryImport } from './routes/treasury'
import { Route as MembersImport } from './routes/members'
import { Route as IndexImport } from './routes/index'
import { Route as ProposalsIndexImport } from './routes/proposals/index'
import { Route as ProfileIndexImport } from './routes/profile/index'
import { Route as ProposalsNewImport } from './routes/proposals/new'
import { Route as ProposalsAddressImport } from './routes/proposals/$address'
import { Route as ProfileEditImport } from './routes/profile/edit'
import { Route as ProfileAddressImport } from './routes/profile/$address'

// Create/Update Routes

const TreasuryRoute = TreasuryImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRoute,
} as any)

const MembersRoute = MembersImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProposalsIndexRoute = ProposalsIndexImport.update({
  id: '/proposals/',
  path: '/proposals/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const ProposalsNewRoute = ProposalsNewImport.update({
  id: '/proposals/new',
  path: '/proposals/new',
  getParentRoute: () => rootRoute,
} as any)

const ProposalsAddressRoute = ProposalsAddressImport.update({
  id: '/proposals/$address',
  path: '/proposals/$address',
  getParentRoute: () => rootRoute,
} as any)

const ProfileEditRoute = ProfileEditImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRoute,
} as any)

const ProfileAddressRoute = ProfileAddressImport.update({
  id: '/profile/$address',
  path: '/profile/$address',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersImport
      parentRoute: typeof rootRoute
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryImport
      parentRoute: typeof rootRoute
    }
    '/profile/$address': {
      id: '/profile/$address'
      path: '/profile/$address'
      fullPath: '/profile/$address'
      preLoaderRoute: typeof ProfileAddressImport
      parentRoute: typeof rootRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditImport
      parentRoute: typeof rootRoute
    }
    '/proposals/$address': {
      id: '/proposals/$address'
      path: '/proposals/$address'
      fullPath: '/proposals/$address'
      preLoaderRoute: typeof ProposalsAddressImport
      parentRoute: typeof rootRoute
    }
    '/proposals/new': {
      id: '/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof ProposalsNewImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/proposals/': {
      id: '/proposals/'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/members': typeof MembersRoute
  '/treasury': typeof TreasuryRoute
  '/profile/$address': typeof ProfileAddressRoute
  '/profile/edit': typeof ProfileEditRoute
  '/proposals/$address': typeof ProposalsAddressRoute
  '/proposals/new': typeof ProposalsNewRoute
  '/profile': typeof ProfileIndexRoute
  '/proposals': typeof ProposalsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/members': typeof MembersRoute
  '/treasury': typeof TreasuryRoute
  '/profile/$address': typeof ProfileAddressRoute
  '/profile/edit': typeof ProfileEditRoute
  '/proposals/$address': typeof ProposalsAddressRoute
  '/proposals/new': typeof ProposalsNewRoute
  '/profile': typeof ProfileIndexRoute
  '/proposals': typeof ProposalsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/members': typeof MembersRoute
  '/treasury': typeof TreasuryRoute
  '/profile/$address': typeof ProfileAddressRoute
  '/profile/edit': typeof ProfileEditRoute
  '/proposals/$address': typeof ProposalsAddressRoute
  '/proposals/new': typeof ProposalsNewRoute
  '/profile/': typeof ProfileIndexRoute
  '/proposals/': typeof ProposalsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/members'
    | '/treasury'
    | '/profile/$address'
    | '/profile/edit'
    | '/proposals/$address'
    | '/proposals/new'
    | '/profile'
    | '/proposals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/members'
    | '/treasury'
    | '/profile/$address'
    | '/profile/edit'
    | '/proposals/$address'
    | '/proposals/new'
    | '/profile'
    | '/proposals'
  id:
    | '__root__'
    | '/'
    | '/members'
    | '/treasury'
    | '/profile/$address'
    | '/profile/edit'
    | '/proposals/$address'
    | '/proposals/new'
    | '/profile/'
    | '/proposals/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MembersRoute: typeof MembersRoute
  TreasuryRoute: typeof TreasuryRoute
  ProfileAddressRoute: typeof ProfileAddressRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProposalsAddressRoute: typeof ProposalsAddressRoute
  ProposalsNewRoute: typeof ProposalsNewRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProposalsIndexRoute: typeof ProposalsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MembersRoute: MembersRoute,
  TreasuryRoute: TreasuryRoute,
  ProfileAddressRoute: ProfileAddressRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProposalsAddressRoute: ProposalsAddressRoute,
  ProposalsNewRoute: ProposalsNewRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProposalsIndexRoute: ProposalsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/members",
        "/treasury",
        "/profile/$address",
        "/profile/edit",
        "/proposals/$address",
        "/proposals/new",
        "/profile/",
        "/proposals/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/members": {
      "filePath": "members.tsx"
    },
    "/treasury": {
      "filePath": "treasury.tsx"
    },
    "/profile/$address": {
      "filePath": "profile/$address.tsx"
    },
    "/profile/edit": {
      "filePath": "profile/edit.tsx"
    },
    "/proposals/$address": {
      "filePath": "proposals/$address.tsx"
    },
    "/proposals/new": {
      "filePath": "proposals/new.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/proposals/": {
      "filePath": "proposals/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
